# Generated by Django 4.0.3 on 2022-03-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='image',
            field=models.ImageField(upload_to='images/headings'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('details', models.TextField(max_length=300)),
                ('main_image', models.ImageField(upload_to='images/products/main')),
                ('secondary_image_1', models.ImageField(null=True, upload_to='images/products/secondary')),
                ('secondary_image_2', models.ImageField(null=True, upload_to='images/products/secondary')),
                ('secondary_image_3', models.ImageField(null=True, upload_to='images/products/secondary')),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.heading')),
            ],
        ),
    ]
