# Generated by Django 4.0.3 on 2022-03-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_heading_image_alter_heading_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/main'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/secondary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/secondary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/secondary'),
        ),
    ]
